packages:
  - ./
catalog:
  '@antfu/eslint-config': ^4.12.0
  '@iconify-json/flag': ^1.2.5
  '@intlify/core': ^10.0.7
  '@intlify/core-base': ^10.0.7
  '@nuxt/eslint': ^1.3.0
  '@nuxt/eslint-config': ^1.3.0
  '@nuxt/icon': ^1.12.0
  '@nuxt/image': ^1.10.0
  '@nuxthub/core': ^0.8.25
  '@nuxtjs/i18n': ^9.5.4
  '@unhead/vue': ^2.0.8
  '@unocss/nuxt': ^66.1.0
  '@unocss/preset-rem-to-px': ^66.1.0
  '@unocss/reset': ^66.1.0
  '@unocss/transformer-directives': ^66.1.0
  eslint: ^9.26.0
  eslint-plugin-format: ^1.0.1
  nimiq-css: ^1.0.0-beta.22
  nuxt: ^3.17.1
  nuxt-og-image: ^5.1.3
  reka-ui: ^2.2.0
  typescript: ^5.8.3
  unocss: ^66.1.0
  unstorage: ^1.16.0
  vue: ^3.5.13
  vue-router: ^4.5.1
  vue-tsc: ^2.2.10
  wrangler: ^3.114.8
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd
